//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spe.gob.ec {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class SrvEventos : global::System.Configuration.ApplicationSettingsBase {
        
        private static SrvEventos defaultInstance = ((SrvEventos)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SrvEventos())));
        
        public static SrvEventos Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("900000")]
        public string Tiempo {
            get {
                return ((string)(this["Tiempo"]));
            }
            set {
                this["Tiempo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("07:00:00 AM")]
        public string HoraInicio {
            get {
                return ((string)(this["HoraInicio"]));
            }
            set {
                this["HoraInicio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22:00:00 PM")]
        public string HoraFin {
            get {
                return ((string)(this["HoraFin"]));
            }
            set {
                this["HoraFin"] = value;
            }
        }
    }
}
